# golangci-lint configuration for Repeater project

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - repeater-design
  skip-files:
    - ".*_test.go"  # Skip test files for some linters

linters:
  enable:
    # Default linters
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Go vet
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis
    - typecheck     # Type checking
    - unused        # Check for unused constants, variables, functions and types
    
    # Additional useful linters
    - gofmt         # Check if code is gofmt-ed
    - goimports     # Check if imports are sorted
    - misspell      # Find commonly misspelled English words
    - gocyclo       # Cyclomatic complexity
    - dupl          # Code clone detection
    - goconst       # Find repeated strings that could be constants
    - unconvert     # Remove unnecessary type conversions
    - prealloc      # Find slice declarations that could potentially be preallocated
    - exportloopref # Check for pointers to enclosing loop variables
    - nolintlint    # Ill-formed or insufficient nolint directives

  disable:
    - deadcode      # Deprecated
    - varcheck      # Deprecated
    - structcheck   # Deprecated
    - scopelint     # Deprecated

linters-settings:
  gocyclo:
    min-complexity: 15  # Allow moderate complexity for CLI tools
    
  dupl:
    threshold: 100      # Allow some duplication in tests
    
  goconst:
    min-len: 3
    min-occurrences: 3
    
  misspell:
    locale: US
    
  goimports:
    local-prefixes: github.com/swi/repeater

issues:
  # Exclude some linters from running on tests files
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - goconst
        - prealloc
    
    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA9003:"  # Empty branch
    
    # Exclude lll issues for long lines in tests
    - path: _test\.go
      linters:
        - lll

  # Maximum issues count per one linter
  max-issues-per-linter: 0
  
  # Maximum count of issues with the same text
  max-same-issues: 0

  # Show only new issues created after git revision
  # new-from-rev: HEAD~1