run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - misspell

linters-settings:
  gofmt:
    simplify: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0